version: '3.8'

services:
  test_db:
    image: postgres:15
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      test_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://test_user:test_password@test_db/test_db
      TEST_ENV: "True"
    ports:
      - "8001:8000"
    networks:
      - app_network
    restart: "no"

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
